Add a build step to check if the committed code has been formatted before the commit.
Signed-off-by: James R. Perkins <jperkins@redhat.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -74,3 +74,21 @@ jobs:
           name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
           path: '**/surefire-reports/*.txt'
 
+  format-check:
+    name: Check Code Formatting
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    steps:
+      - uses: actions/checkout@v2
+      - name: Set up JDK 11
+        uses: actions/setup-java@v2
+        with:
+          java-version: 11
+          distribution: 'temurin'
+          cache: 'maven'
+      - name: Format Source
+        run: "mvn install -pl ide-config && mvn -B -pl '-ide-config' formatter:format"
+      - name: Check for changes
+        run:  |
+          [ -z "$(git status --porcelain=v1 2>/dev/null)" ] || (echo -e "::error ::Changes have been found\n$(git status --porcelain)" && exit 1)
+
